### ISSUE TITLE
autogen.sh eats $1 instead of passing to configure

### ISSUE THREAD

**Issue by mhaas** [wifidog/wifidog-gateway#103]
If you run

    ./autogen.sh --enable-cyassl

then *enable--cyassl* gets saved to *$BUILDROOT* and weird stuff ensues.

    if [ "X$1" != "X" ]
    then
        BUILDROOT=`echo "$1" | sed 's/^[^=]*[=]//'`
        [..]
       CC=${BUILDROOT}/build_mipsel/staging_dir/bin/mipsel-linux-uclibc-gcc

**Comment by acv** [comment]
This was needed back in the days to build packages. Is this still needed? Does it even work?

**Comment by mhaas** [comment]
It is not needed on current Openwrt sdks. You can probably set $CC and be good.

**Comment by acv** [comment]
Cool, I should get an openwrt SDK and play with it, last time I tried in the summer of '04 it was a pretty rough system.

**Comment by mhaas** [comment]
With current OpenWRT SDKs, you need the Makefile (package recipe) we were talking about in that other ticket. You can probably just use their CC and make that work. With the Makefile, I only ever update the version and re-compile. That's tolerable for me, so I have no use for the current hack to directly use a cross-compiler.

**Comment by acv** [comment]
Then PR should be made with:

1. This hack removed.
2. A readme type file with up to date and working build instructions.
