### ISSUE TITLE
Update doc/README.developers.txt

### ISSUE THREAD

**Issue by mhaas** [wifidog/wifidog-gateway#105]
* Code style
* Contribution workflow (git flow)
* Replace reference to subversion $id field
* Where is that user documentation in SGML format?
* What's sourceforge? :>
* http://listes.ilesansfil.org/cgi-bin/mailman/listinfo/wifidog 404
* homepage at http://www.ilesansfil.org/wiki/WiFiDog 404

**Comment by florida63** [comment]
May be we should use https://github.com/wifidog/wifidog-gateway/wiki to refocus everything here.

**Comment by mhaas** [comment]
I fixed this a while ago.

Wiki.. Not sure. Probably better to have it in the source tree along the code.
