### ISSUE TITLE
create openwrt wifidog feed repo

### ISSUE THREAD

**Issue by champtar** [wifidog/wifidog-gateway#107]
Hi,

can one of @acv, @benoitg, @florida63 create a new git repo like wifidog/old-openwrt-feed,
so we can put AA and BB openwrt makefile in it, with a quick howto, ...

Thanks in advance

**Comment by florida63** [comment]
I can create a repository wifidog-feed if it's useful. 

No objection?

**Comment by acv** [comment]
Go ahead. We can always remove it later if we need to.

**Comment by sinkcup** [comment]
don't create for BB AND CC, should fork openwrt/packages

**Comment by champtar** [comment]
@sinkcup, we still need a separate feed for AA and BB
i feel you don't understand how feed works

**Comment by mhaas** [comment]
@champtar would it make sense to create a new repository (feed) which only contains the makefile for the old releases? That you won't have a feed which duplicates all packages for the old release.

The underlying assumption is that OpenWrt will only update the CC feed.

**Comment by champtar** [comment]
@mhaas yes that's exactly what i'm trying to do with this issue.

**Comment by mhaas** [comment]
FYI, wifidog and wifidog-tls are now building via https://github.com/wifidog/packages/tree/wifidog-experimental

**Comment by florida63** [comment]
Good

**Comment by mhaas** [comment]
@acv do you have the ability to create a new, empty repo for makefiles for the old openwrt releases?

**Comment by florida63** [comment]
@mhass: I just create old-openwrt-feed.

**Comment by databeille** [comment]
@acv, @mhass Guys, how do you plan to organize old-openwrt-feed ?

**Comment by databeille** [comment]
@mhaas nice job for wifidog-tls :+1: ; I have successfully build a openWRT BB package, arch: ar71xx.

**Comment by acv** [comment]
I never knew much about openwrt packaging, so I'm staying out of it. I only ever used wifidog on plain Linux and others in ISF (Benoit or Phil usually) did the openwrt stuff.

**Comment by mhaas** [comment]
Well, I don't know.. I guess if you put the files into net/wifidog/ everything will be OK.

**Comment by mhaas** [comment]
If you want different makefiles for different releases, then probably do different branches. At least the BB SDK supports checking out different branches conveniently.
