### ISSUE TITLE
DRY: merge NEWS to ChangeLog, and delete NEWS 

### ISSUE THREAD

**Issue by sinkcup** [wifidog/wifidog-gateway#108]
ChangeLog and NEWS have some repeated content, follow DRY, we can merge NEWS into ChangeLog. like https://www.virtualbox.org/wiki/Changelog, content like:

    ##1.2.0 (released 2015-03-18)
    
    * Add possibility to use domain whitelist in conf, and auto pass subdomains.

    ##1.1.5 (released 2008-03-24)
    
    * First supported version on OpenWRT kamikaze

![2015-03-19 10 33 26](https://cloud.githubusercontent.com/assets/4971414/6723616/8da59a94-ce25-11e4-8745-685c2275054d.png)

**Comment by mhaas** [comment]
Good idea.

I would like to tackle this.

Should we includes dates for individual changes as done on NEWS?

**Comment by acv** [comment]
It's not needed. As long as versions are clear.

**Comment by acv** [comment]
This issue is resolved I think.
