### ISSUE TITLE
1.2.0 a bit premature?

### ISSUE THREAD

**Issue by mhaas** [wifidog/wifidog-gateway#109]
Hey there,

@sinkcup tagged and released 1.2.0 on Github. I think that's a bit premature, given that the changelog has not been fully updated. We should have some kind of consensus (or BDFL decision) on when to release. Now, we have people single-handedly tagging releases when they're not as ready as they could be.

**Comment by florida63** [comment]
@sinkcup: I am of the same opinion as @mhaas.

In addition, before a tagged version 1.2.0 maybe would it make a pre-realease to test because there were many changes. 1.2.0_alpha for exemple.

**Comment by mhaas** [comment]
Not sure if we need _alpha, everyone knows that x.y.0 releases are broken ;)

**Comment by sinkcup** [comment]
It's a bit premature. maybe delete it is an good choice.
I will try to find a old commit ID, and tag it, such as 1.0.0, 1.1.5.
@florida63 If we use alpha, we should use 1.2.0-alpha.1 not 1.2.0_alpha
please see this docs http://semver.org/lang/zh-CN/ 
1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0- rc.1 < 1.0.0

**Comment by sinkcup** [comment]
I just want use tag as soon as possible, otherwise people use master, it's more unstable...
I will try to find the commit id of 1.1.5, and tag it.
You are right, should not release a tag by one person, need discussion

**Comment by florida63** [comment]
1.1.4 --> https://github.com/wifidog/wifidog-gateway/commit/2f7b99ce80e831850baf82e689aa12919a6268df

**Comment by mhaas** [comment]
I'll fix the changelog later today. I should have some time then.

**Comment by sinkcup** [comment]
Sorry to trouble you.
I have delete 1.2.0, and add old tags.
I will become immersed in my work. See you.

**Comment by acv** [comment]
This is a pretty good argument for having a 2 branch repo... With 2 branches master can be stable.

**Comment by acv** [comment]
Do we need a BFDL? I mean I can do it if that's desired. Focus would be on the B and not so much the D ;-).

**Comment by mhaas** [comment]
We don't need a dictator if everything happens as I command.. j/k. Just saying, there should be a consensus on "let's release" before we release.

**Comment by databeille** [comment]
@mhaas I agree with you

**Comment by mhaas** [comment]
Time for a release?

**Comment by florida63** [comment]
This document (https://github.com/wifidog/wifidog-gateway/blob/master/NEWS) inconsistency on the layout. 

Otherwise ok to release 1.2.0

**Comment by florida63** [comment]
For me it's ok.

**Comment by mhaas** [comment]
Pinging @acv and @sinkcup. I think @sinkcup should do the release :)

**Comment by florida63** [comment]
@champtar, @benoitg, @databeille. What about you?

**Comment by sinkcup** [comment]
OK :+1: 
create 1.2.0 using commit 5cb3a3623533bc51ce2adf5590b7d9ef9b166302 ?

**Comment by florida63** [comment]
@sinkcup:  yes

**Comment by sinkcup** [comment]
@florida63 @mhaas  done :)

**Comment by florida63** [comment]
@mhaas: you might have to wait another

Perhaps, add the big changes comment in https://github.com/wifidog/wifidog-gateway/releases/tag/1.2.0

it lacks some useful files in your tar.gz (see old tar.gz we sourceforge)
