### ISSUE TITLE
cause the server pressure is very big

### ISSUE THREAD

**Issue by eggbucket** [wifidog/wifidog-gateway#112]
All requests to intercept, cause the server pressure is very big, what method can reduce the server pressure?
For example: video request innumerable links are redirected to the server

**Comment by acv** [comment]
Unfortunately, there's no magic bullet. A captive portal will have to intercept all HTTP connections.

**Comment by mhaas** [comment]
Is this a problem in reality? Does performance suffer?

**Comment by eggbucket** [comment]
The cache can do?For example, some background process will request a port 80 and is a large amount of the request

**Comment by acv** [comment]
Caching, if desired should be implemented upstream from the gateway with something like Squid.

Closing.
