### ISSUE TITLE
Integrate coverity with travis

### ISSUE THREAD

**Issue by mhaas** [wifidog/wifidog-gateway#138]
It's quite straightforward: https://scan.coverity.com/travis_ci

Once set up, we can trigger coverity through commits to a special branch.

Assigning to @acv as he is the master of coverity.

**Comment by acv** [comment]
One PITA is that coverity will run with and without SSL on both gcc and clang.

**Comment by acv** [comment]
Side effect seems to be that you always pass since it doesn't find any different number of issues between build the last two builds it runs.

**Comment by acv** [comment]
I could make the branch only run gcc + SSL by keeping its .travis.yml distinct. We just gotta remember to fix it when/if we push to it a new .travis.yml file.

**Comment by mhaas** [comment]
Sounds good. I wonder if we can limit the coverity run to only one entry in the build matrix. Seems like what you are suggesting is the current best practice :/

https://github.com/travis-ci/travis-ci/issues/1975

**Comment by acv** [comment]
Yeah, that's where I got the idea...

**Comment by acv** [comment]
So I updated the coverity_scan branch and travis appears to be doing "the right thing" and only doing gcc+SSL.

**Comment by mhaas** [comment]
Awesome.
