### ISSUE TITLE
TrustedMac duplicated if present multiple times in the list

### ISSUE THREAD

**Issue by florida63** [wifidog/wifidog-gateway#145]
If we capture in wifidog.conf

TrustedMACList 00:b0:D0:FE:7C:2A,00:b0:D0:FE:7C:2A,00:b0:D0:FE:7C:2A

obtained:
root@Auz2:/etc/init.d# wdctl status
WiFiDog status

Version: 1.2.0
Uptime: 0d 0h 0m 9s
Has been restarted: no
Internet Connectivity: yes
Auth server reachable: no
Clients served this session: 0

0 clients connected.

Trusted MAC addresses:
  00:b0:D0:FE:7C:2A
  00:b0:D0:FE:7C:2A
  00:b0:D0:FE:7C:2A

There are no duplicate check

**Comment by acv** [comment]
Since we already seek to the end of the list to insert, we might as well have it check as it scans the list.

**Comment by florida63** [comment]
thanks for title

**Comment by acv** [comment]
Incidentally, most of the config makes no unique checks.

**Comment by acv** [comment]
Plaisir ;-)

**Comment by acv** [comment]
The fix is in.
