### ISSUE TITLE
Time for a release 1.2.1?

### ISSUE THREAD

**Issue by florida63** [wifidog/wifidog-gateway#157]
The latest patches require a realease

**Comment by acv** [comment]
Sure, update NEWS and cut the release.

**Comment by mhaas** [comment]
Didn't someone report a segfault a couple of hours ago?

Am 24. März 2015 14:52:47 MEZ, schrieb Alexandre Carmel-Veilleux <notifications@github.com>:

**Comment by acv** [comment]
1.2.0 has a known segfault in `src/util.c:get_status_text()` that would be fixed by a 1.2.1.

**Comment by mhaas** [comment]
Ok. Then go for it.

Am 24. März 2015 15:03:13 MEZ, schrieb Alexandre Carmel-Veilleux <notifications@github.com>:

**Comment by florida63** [comment]
update https://github.com/wifidog/wifidog-gateway/releases/tag/1.2.0

**Comment by mhaas** [comment]
1.2.0 does not even build ;) good thinking on the update.

**Comment by acv** [comment]
I say now is a great time.

**Comment by sinkcup** [comment]
...
We have made a mistake about git flow. master should ready for release at all times.
E.G.
if the next mileston after 1.2.0 is 1.3.0, if there is a urgent bug, we should release 1.2.1 from master.
if the next mileston after 1.2.0 is 1.2.1, if there is a urgent bug, we should move all issues to 1.2.2, then fix it and release 1.2.1 from master.

**Comment by mhaas** [comment]
Master is absolutely ready for a release! We have had only fixes and one very minor feature.

**Comment by sinkcup** [comment]
I know, code had been tested before merge into master.
I means can we move other issues, and release 1.2.1 now?
The best time for releasing 1.2.1 is 15 days ago, secondly it's now.

**Comment by mhaas** [comment]
Sure! I think nobody ever felt like releasing .1, but it's time!

Am 16. April 2015 15:22:18 MESZ, schrieb sinkcup <notifications@github.com>:

**Comment by acv** [comment]
+1

**Comment by sinkcup** [comment]
OK, I do it now.

**Comment by sinkcup** [comment]
I see the `NEWS` and the version in `configure.in` are correct, so I have released 1.2.1.
Is it right? @acv

**Comment by mhaas** [comment]
I am not quite sure if we have everything in NEWS, e.g. Some refactoring ie missing. But it's mostly complete.

**Comment by acv** [comment]
I don't know if refactoring that don't affect functionality really belong in a NEWS files anyway. If they do, it's as a single line.

**Comment by mhaas** [comment]
This is a very good release, by the way. Lots of polishing!

![You're awesome](https://imgur.com/ANCygtO)
