### ISSUE TITLE
immediate disconnect feature

### ISSUE THREAD

**Issue by florida63** [wifidog/wifidog-gateway#17]
Patch to add this functionality being available here (http://dev.wifidog.org/ticket/465) it would be wise to integrate to a maximum of users (testers) can be recovered bugs.

**Comment by acv** [comment]
Do we want to merge this in before or after cutting the next release?

**Comment by florida63** [comment]
I just committed three patches in a specific branch.

no time to test now.

**Comment by acv** [comment]
PR #82 is for this issue.

**Comment by mhaas** [comment]
Fixed in #82.
