### ISSUE TITLE
how to add traffic control

### ISSUE THREAD

**Issue by strong46066999** [wifidog/wifidog-gateway#197]
use ifb or imq?

**Comment by acv** [comment]
I believe this is orthogonal to WifiDog and should be down at the underlying O/S level. That said I don't really know much about traffic shaping / QoS on Linux in general.

A major limitations for this is that wifidog is compatible with some pretty old platforms (i.e.: RHEL/CentOS down to like RHEL3 and OpenWRT versions from the last 10 years.)

**Comment by acv** [comment]
Maybe we could add hooks at various places in the firewall processing code to shell out to some shell script and allow you to arbitrarily hook up ifb, imq or whatever else you want?

**Comment by t123yh** [comment]
I think in the further versions we may execute scripts transmitted from server(or script in local and parameters from server) in order to modify some QoS rules for each user.
