### ISSUE TITLE
Add a new config section to switch on new protocol

### ISSUE THREAD

**Issue by t123yh** [wifidog/wifidog-gateway#213]
Many actions in the WiFiDog Protocol is lacking in features. For example, the PortalScriptPathFragment does not provide a token of user for the server. That makes the redirection to the url the user is trying to fetch before signing in hard. But if we modify the protocol directly there may be compatibility problems. So can we just add a new section in the configuration file such as "NewProtocol yes" to enable new features added to WiFiDog?

**Comment by mhaas** [comment]
Adding a new query parameters probably should not break stuff.

Couldn't the portal website simply set a cookie with the redirect url? I am a bit hazy on the current implementation right now.

**Comment by acv** [comment]
I'm not really seeing what is to do here.
