### ISSUE TITLE
build failure with musl-libc

### ISSUE THREAD

**Issue by karlp** [wifidog/wifidog-gateway#221]
Minor tweaks to include more "proper" headers.

See fix and patch at https://github.com/openwrt/packages/pull/1407

**Comment by acv** [comment]
@karlp Can you submit the patch as a PR here?

**Comment by karlp** [comment]
Not me, I've never even used wifidog, I'm just trying to make sure different groups are actually hearing about things, instead of people patching in the dark without upstream even knowing about the issue.

**Comment by acv** [comment]
Fair enough.

**Comment by acv** [comment]
I'll try and find some time in the near future (probably mid-July realistically) to test this patch with glibc.

**Comment by mhaas** [comment]
If we could get a PR, the builders would at least compile test it. But I am also super busy:(
