### ISSUE TITLE
Interested in the Prerouting portion on Wifidog

### ISSUE THREAD

**Issue by iDVB** [wifidog/wifidog-gateway#228]
I'm interested in setting things up so that when people connect to my Wifi AP (RaspberryPi) they automatically get a browser popup that directs them to my AP's auth page. Similar to what you see for coffee shops etc. 

Is there a way to set this up using wifidog.... or maybe its possible natively in unix?

**Comment by t123yh** [comment]
Just use default WiFiDog's settings, then the authorization page will appear automatically.
The mobile phone sends a request to its Internet-connection-checking-server, and if it gets a redirect request, then it will show the login page (destination of the redirect).

**Comment by iDVB** [comment]
Thanks @t123yh is there a way to get just that portion working? I already have a nodejs server that I want to serve up the actual page that things get redirected to.

**Comment by mhaas** [comment]
Is your Raspberry Pi different from your AP, i.e. do you have two physical devices there?
What does your nodejs server do?

To phrase my question differently: do you already have a fully working captive portal and just want people connecting to rasppi to use that?

**Comment by iDVB** [comment]
Nope the Rpi and AP are one and the same thing. And yes, I already have an nodejs web application and just want people to be default driven to it as well as locked to it, all other urls blocked.

**Comment by iDVB** [comment]
Essentially, I just want it to ALWAYS redirect to my server. I do NOT want people to access any other site then the local one I default them to.

**Comment by mhaas** [comment]
That is easily done with a single iptables rule: http://unix.stackexchange.com/questions/203791/how-to-redirect-all-http-request-to-a-local-web-server

**Comment by iDVB** [comment]
Thanks! I'll give this a go
