### ISSUE TITLE
how many people does wifidog support in openwrt ？

### ISSUE THREAD

**Issue by strong46066999** [wifidog/wifidog-gateway#229]
what is wifidog finally mean to do ? an't we do the best?
In my mind , the iptables rules number = n * (loggined user number) n is fix, n may be 2. or 3 or others.
with too many people（like 2000）, this is very very inefficient,  with every every packet check in kernel.
can we drop iptables, do our check logic in netfiler ??  In Other word, user nefilter better fit our need.

**Comment by t123yh** [comment]
Wifidog is not a commercial solution.
You can use x86 routers for  higher performance.

**Comment by acv** [comment]
If you need very high throughput, I suggest you look at Aruba networks or similar...
