### ISSUE TITLE
Debian install ?

### ISSUE THREAD

**Issue by cmelian** [wifidog/wifidog-gateway#234]
Hi,
Is it possible to install Wifidog-gateway on a debian box ?
Thank you

**Comment by mhaas** [comment]
Yes!

**Comment by cmelian** [comment]
Cool !
I tried to follow steps from http://dev.wifidog.org/wiki/doc/install/debian but no succes. Is there any updated doc for this ? Thank you.

**Comment by cmelian** [comment]
It's ok. I found missing pieces. On my fresh VM I forgot to install 
apt-get install automake make libtool
