### ISSUE TITLE
Build wifidog for openwrt chaos_calmer/15.05

### ISSUE THREAD

**Issue by deivisonrpg** [wifidog/wifidog-gateway#243]
Hi anyone build ipk package WiFiDog 1.3.0 for chaos-calmer/15.05 i try to build and don't make work.
The question WiFiDog 1.3.0 work on CC?
Tks all

**Comment by deivisonrpg** [comment]
I have compile for CC using the toolchain has been generated and the ipk, however to install and try to run me back Ash: wifidog: not found.
[wifidog_1.3.0-1_ar71xx.ipk.zip](https://github.com/wifidog/wifidog-gateway/files/109860/wifidog_1.3.0-1_ar71xx.ipk.zip)

Can anyone confirm if this wifidog version works on openwrt CC?

**Comment by deivisonrpg** [comment]
I try to use ipk from snapshots repository openwrt https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/packages/wifidog_1.3.0-1_ar71xx.ipk and get same error. 
incompatibility for openwrt or wifidog?

**Comment by mhaas** [comment]
That's... odd. I looked at the Openwrt IPK file and everything is in place. What happens if you execute /usr/bin/wifidog directly? Can you run ldd on the file?

**Comment by mhaas** [comment]
Can you run:

    file /usr/bin/wifidog

It should report the interpreter, something like /lib/ld-uClibc.so.0 - does that file exist?

**Comment by deivisonrpg** [comment]
I @mhaas 
If i try to run commands: file, ldd or execute directly from /usr/bin wifidog or wdctl i have same error:
-ash: XXXX: not found (XXXX is the file)

![Print ssh](https://cloud.githubusercontent.com/assets/1278305/12695768/410f13ea-c73f-11e5-9ed2-d8c6bfa59d24.png)

I try my ipk and openwrt ipk same thing.
If i install 1.2.1 ipk works fine.

**Comment by mhaas** [comment]
That's.. weird. I don't have time to reproduce right now, but I will take a look next week (-ish).

**Comment by demslob** [comment]
is there anyone with 15.05 ramips device who can give me ipk?

**Comment by mgiller** [comment]
Hi

I have the same problem, have you find a solution?

tks

**Comment by deivisonrpg** [comment]
Hi, no i give up.

**Comment by turanmete-bhr** [comment]
Any update how you solved it ?

**Comment by turanmete-bhr** [comment]
I also got the same situation after trying to compile 1.3.0.
Then I tried to compile 1.2.1 and use it. But I got built error like

protocol.c:534:10: warning: implicit declaration of function 'open' [-Wimplicit-function-declaration]
     fd = open(path, O_RDONLY);
          ^
protocol.c:534:21: error: 'O_RDONLY' undeclared (first use in this function)
     fd = open(path, O_RDONLY);
                     ^
protocol.c:534:21: note: each undeclared identifier is reported only once for each function it appears in
make[5]: *** [protocol.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2

**Comment by turanmete-bhr** [comment]
I think the problem is mainly about C compiler. When you are changing compiler to the older one (Menconfig - Advanced options - c library) still getting error but somehow its working I mean sending requests to auth server.

**Comment by kuzjnvn** [comment]
anybody can make wifidog ipk for 14.07 openwrt ar71xx ?
thanks so much

**Comment by mm1860** [comment]
./wifidog  ,command like this
