### ISSUE TITLE
FAQ Link changed

### ISSUE THREAD

**Issue by worsedoughnut** [wifidog/wifidog-gateway#252]
FAQ link in the readme is:

https://github.com/wifidog/wifidog-gateway/blob/master/src/FAQ

Should be:

https://github.com/wifidog/wifidog-gateway/blob/master/FAQ

**Comment by KazukiShimada** [comment]
HI.
nice work!
Thanks.

**Comment by florida63** [comment]
fixed in #253, thanks.

**Comment by worsedoughnut** [comment]
FYI: Previously missed identical issue #242 should be close as well.
