### ISSUE TITLE
src/gateway.c line 370

### ISSUE THREAD

**Issue by fbichina** [wifidog/wifidog-gateway#263]
Line 370 in src/gateway.c
"if ((!config) && (!config->pidfile))"
Isn't it wired to write this ???

**Comment by qianguozheng** [comment]
something wrong ?

**Comment by fbichina** [comment]
`if ((!config) && (!config->pidfile))`
equals
`if ((config==NULL) && (config->pidfile == NULL))`
if "config" is NULL , how to get "pidfile" from NULL??

**Comment by qianguozheng** [comment]
if config is NULL then !config is true. it will not get the pidfile

**Comment by fbichina** [comment]
@qianguozheng 
Yep, if config is NULL, which means !config is true and the left part of "&&" operation is true, it will go to see whether the right part is also true. That means when config is NULL, it will excute (!config->pidfile)...But how to get a thing from NULL ???

**Comment by qianguozheng** [comment]
Indeed, it MUST be wrong

**Comment by poolborges** [comment]
That condition is not valid when only pid is null. 
So it must have a or between righ side and left side
We read: when conf is null ou pid is null do something.
if ((!config) || (!config->pidfile))

The code will be better to read if is write li this

if ((config == NULL) || (config->pidfile || NUL))

**Comment by poolborges** [comment]
if ((config == NULL) || (config->pidfile == NULL))

**Comment by fbichina** [comment]
@qianguozheng NONONONO，，，，It should be like "if( config && config->pid )" cause the next line is to use the config->pid....So the "config" and "config->pid" both can not be null.
For more pretty, it could be written like "if (config != NULL && config->pid != NULL) "  Ha.

**Comment by qianguozheng** [comment]
So this issue can be closed

**Comment by poolborges** [comment]
Depende of whow important is to save pid

**The Original is**
``
/* save the pid file if needed */
if ((!config) && (!config->pidfile))
    save_pid_file(config->pidfile);
``
**The Suggest**
if ((config == NULL) || (config->pidfile == NULL)){
    debug(LOG_ERR, "Could not get PID, exiting...");
    exit(1);
}else{
    save_pid_file(config->pidfile);
}
