### ISSUE TITLE
Spawning worker thread

### ISSUE THREAD

**Issue by Tr4cer0ute** [wifidog/wifidog-gateway#270]
Hi all,

I was playing around Wifidog gateway and I'm getting this weird msg from log.

> [6][Fri Dec  9 19:46:22 2016][27193](gateway.c:463) Received connection from 192.168.17.107, spawning worker thread

Will this affect the user experience or cause abnormal behaviour? 

Best

**Comment by LGaitan** [comment]
Hi,

You don't have to worry, this is just a message for debug purposes.
It just indicates wifidog is reading a received connection onto his webserver.


It is declared in gateway.c line 472
```c
/*
 * We got a connection
 *
 * We should create another thread
 */
debug(LOG_INFO, "Received connection from %s, spawning worker thread", r->clientAddr);
```
