### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by Tr4cer0ute** [wifidog/wifidog-gateway#272]
Hi,

How can we stress test a WD's Gateway? 

Best.

**Comment by 2isr** [comment]
We use the "clif perspective" software which performs load tests. Opening / Redirecting page. We can do everything with this software

**Comment by mhaas** [comment]
I believe I have a stress test script posted somewhere. I don't have the link as I am on mobile.

Am 15. Dezember 2016 00:03:39 MEZ, schrieb Tr4cer0ute <notifications@github.com>:
>Hi,
>
>How can we stress test a WD's Gateway? 
>
>Best.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wifidog/wifidog-gateway/issues/272

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Tr4cer0ute** [comment]
@mhaas Please do
