### ISSUE TITLE
Wifidog Installation on ubuntu/ Debian

### ISSUE THREAD

**Issue by oscarmerd** [wifidog/wifidog-gateway#274]
wifidog gateway 1.3.0  doesn't build with ./configure , make and make install

error: configure file not found
error: make and make install file not found

Please assist
![1](https://cloud.githubusercontent.com/assets/25921457/23154723/51e4a39a-f7dd-11e6-95f6-c8ecafa1b2e0.png)
![2](https://cloud.githubusercontent.com/assets/25921457/23154729/5787af72-f7dd-11e6-9a44-1452cf5ddd35.png)
![3](https://cloud.githubusercontent.com/assets/25921457/23154733/59b98a22-f7dd-11e6-8042-eda6210c4ecf.png)

**Comment by mhaas** [comment]
Please use the most recent release 

Am 21. Februar 2017 08:28:02 MEZ schrieb oscarmerd <notifications@github.com>:
>wifidog gateway 1.3.0  doesn't build with ./configure , make and make
>install
>
>error: configure file not found
>error: make and make install file not found
>
>Please assist
>![1](https://cloud.githubusercontent.com/assets/25921457/23154723/51e4a39a-f7dd-11e6-95f6-c8ecafa1b2e0.png)
>![2](https://cloud.githubusercontent.com/assets/25921457/23154729/5787af72-f7dd-11e6-9a44-1452cf5ddd35.png)
>![3](https://cloud.githubusercontent.com/assets/25921457/23154733/59b98a22-f7dd-11e6-8042-eda6210c4ecf.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wifidog/wifidog-gateway/issues/274

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by oscarmerd** [comment]
Similarly the same error, tried 1.3.0

**Comment by oscarmerd** [comment]
Am i missing something on. I did try with original version it works perfectly that is 2009 version, but the latest the command doesn't work.
Please assist.

Merd

**Comment by lgaitan** [comment]
if you are cloning directly from github, try executing ./autogen.sh first. It'll generate the autoconf files.

**Comment by oscarmerd** [comment]
Still ain't working would this is what i get as the output
![mm](https://cloud.githubusercontent.com/assets/25921457/23184214/f0308d74-f84c-11e6-8bdd-8660852cf0ce.png)

**Comment by lgaitan** [comment]
make sure you have libtool and autoconf packages, try apt-get install autotools autoconf automake libtool

**Comment by oscarmerd** [comment]
Thank you so much, I installed successfully.
