### ISSUE TITLE
Can't active login with facebook

### ISSUE THREAD

**Issue by mrsantran** [wifidog/wifidog-gateway#279]
How to enable login with facebook ?
i use opentwrt and wifidog 1.2.1

error like image:

![screen shot 2017-06-21 at 7 28 50 pm](https://user-images.githubusercontent.com/21286108/27384110-ebf06058-56b7-11e7-9a4a-828ddaaef59b.png)
![screen shot 2017-06-21 at 7 28 35 pm](https://user-images.githubusercontent.com/21286108/27384109-ebed157e-56b7-11e7-99dc-51ad9faf8f2e.png)

**Comment by benoitg** [comment]
Looks like an authentication server problem, not a wifidog gateway one.
