### ISSUE TITLE
wifi connection issues

### ISSUE THREAD

**Issue by pepijnvdk** [wifidog/wifidog-gateway#292]
Hi, we are using a beagle bone green wireless with the debian image kernel 4.9.38-ti-r49 provided by seeedstudio with wifi dog

The main issue we are experiencing is that every now and then, when a user is trying to connect to the access point from their phones or computers, an error occurs that says “failed to connect”. 

It is solved by turning the beaglebone off and then on again, but it can sometimes take up to 10 tries or more for it to work. 

The second issue is that once the Beaglebone is connected and has an IP address, it can’t be connected to another WiFi network, it shows a message saying “oops already connected”. 

The only way to connect to a second network, is to turn the first router off. 

The last issue is that when the Beaglebone becomes disconnected from the wifi network, the user needs to turn the Beaglebone off and back on for it to reconnect.

**Comment by benoitg** [comment]
None of those appear to be wifidog-gateway issues.  In any event, there is not much we can do to help:

1. You may have better luck at https://github.com/Pillar1989/wifidog-server, who seem to be developing your solution.
1. For some reason, they seem to recommend an older, unmodified fork of wifidog-gateway at: https://github.com/Pillar1989/wifidog-gateway
