### ISSUE TITLE
Invalid request path ''

### ISSUE THREAD

**Issue by Guoqing-Wu** [wifidog/wifidog-gateway#32]
I cloned this repo and compiled it, then I installed it on BarrierBreaker. It works well. But I am getting a lot of Invalid request path ''. Any advice?

**Comment by acv** [comment]
I would suggest if you can to capture the network traffic that hits port 80 on your gateway for a few minutes around those requests time and then compare the request received over the network. This is possibly invalid/malformed HTTP.

**Comment by sinkcup** [comment]
there are too many "Invalid request path", so we should hide it, only show at debug model.

**Comment by acv** [comment]
This will no longer print, it was debug code that should've been removed a long time ago.
