### ISSUE TITLE
Multiple IP addresses for each auth servers support

### ISSUE THREAD

**Issue by Sannis** [wifidog/wifidog-gateway#38]
Have you plans for such functionality? I will be very useful if auth server hostname is handled with round-robin or geo-DNS service.

**Comment by acv** [comment]
Does the ipset functionality adequately address this bug? Every connection to the auth server does an independent `gethostbyname()`

**Comment by mhaas** [comment]
@acv, I think the issue here is the clients being blocked. That is probably independent of the gateway doing a *gethostbyname()* when it talks to the auth server.

**Comment by acv** [comment]
That's why I was thinking ipset took care of that half.

**Comment by mhaas** [comment]
Yes, ipset handles this.
