### ISSUE TITLE
Issue where wifidog will never pass a new token upstream unless a

### ISSUE THREAD

**Issue by florida63** [wifidog/wifidog-gateway#56]
Reported and corrected bug in DD WRT
http://svn.dd-wrt.com/changeset/20675

to be confirmed

**Comment by acv** [comment]
Something's fishy with that fix.

It seems to fix a symptom (auth for a client already in the client_list does not use new token) without actually putting the new token in the client entry.

**Comment by acv** [comment]
Right fix would be to Lock the client list, find client by IP/Mac and update client->token (freeing previous value if not null) just before the call to authenticate.

Ideally by implementing the logic as a `client_list_update_token()` call.

Then auth.c will work regardless.

**Comment by acv** [comment]
I suspect the current code is already fixed by 0a7bb07f.

**Comment by acv** [comment]
Confirmed.

**Comment by florida63** [comment]
That explains why I had no problem.

"Good eye"
