### ISSUE TITLE
FirewallRule allow domain, and auto pass subdomain

### ISSUE THREAD

**Issue by sinkcup** [wifidog/wifidog-gateway#65]
now wifidog FirewallRule only allow ip, if it can support domain and auto pass subdomain, it will be more useful, so I write the code.

eg.

`FirewallRule allow tcp to example.com`

**Comment by databeille** [comment]
Very nice !
Is iptables able to handle domains on dynamic or non transparent load balanced IP(s) ? (ex. crl.startssl.com)
