### ISSUE TITLE
if http uri has port, wifidog can't redirect it

### ISSUE THREAD

**Issue by sinkcup** [wifidog/wifidog-gateway#67]
e.g.

    http://www.chinatcc.gov.cn:8080/

**Comment by sinkcup** [comment]
now wifidog redirect 80 port by iptables, how to catch all http request on any port like 8080,1234?
I have no idea now ...

**Comment by acv** [comment]
You can't... Doubly so if they use HTTPS.

**Comment by acv** [comment]
There's no way to fix this (within reason). Closing.
