### ISSUE TITLE
move popular_servers from hard code to config

### ISSUE THREAD

**Issue by sinkcup** [wifidog/wifidog-gateway#78]
now `src/centralserver.c` has a hard code "popular_servers", it should in `wifidog.conf`, then user can change it very easy.
In some country (e.g. China), users can't access www.google.com, and it had been "DNS cache poisoning", so can't use it for DNS health checking.

**Comment by acv** [comment]
Do you have time to implement this? Sounds like a great idea.

**Comment by sinkcup** [comment]
I will do it in this week, before next tag release

**Comment by sinkcup** [comment]
I have finish it, should I move this to milestone 1.2.1 ?
If not, after some commits, it will be hard to merge.

**Comment by mhaas** [comment]
Sounds good, just make a pull request.

**Comment by sinkcup** [comment]
CI is great!
this pull request CI have been successful, I should not merge my code, someone review and merge it, will be better.

**Comment by sinkcup** [comment]
I forgot to show screenshot
![2015-04-09 17 40 18](https://cloud.githubusercontent.com/assets/4971414/7066365/61bd7214-def4-11e4-848d-7d28b502479b.png)
![2015-04-09 18 12 17](https://cloud.githubusercontent.com/assets/4971414/7066374/7ee1192c-def4-11e4-8789-c30b0e07cd76.png)
![2015-04-09 18 23 34](https://cloud.githubusercontent.com/assets/4971414/7066377/828415fc-def4-11e4-95de-3a73546604ac.png)
