### ISSUE TITLE
NetBSD support, failed experiment?

### ISSUE THREAD

**Issue by acv** [wifidog/wifidog-gateway#83]
There's a fair bit of code for NetBSD support, particularly in `util.c`, is this code doing anything other than taking up space and making things complicated?

Has the support for NetBSD ever been finished? Does it work? Does it still work?

I'm inclined to axe it all.

**Comment by mhaas** [comment]
Google did not reveal anything. Sean from cu wireless did the port and their SVN does not load for me.

**Comment by acv** [comment]
Yep, seems dead.

**Comment by mhaas** [comment]
Then.. kill it, I guess. Git revert is always an option.

**Comment by acv** [comment]
Code is removed, issued "resolved".
