### ISSUE TITLE
Opening the firewall if the auth servers are all unreachable

### ISSUE THREAD

**Issue by florida63** [wifidog/wifidog-gateway#90]
see (http://dev.wifidog.org/ticket/92).

**Comment by acv** [comment]
From source:

> The last 2 attachments are a patch from Alex Nault from Zapbsl, compiled and tested by gbastien.
> 
> Works fine, but when the auth server is down and the auth-is-down ruleset is empty, then it does not redirect to the Uh ho! message page as it should do. If anyone has any idea why it doesn't, let me know. The code is not committed yet.

**Comment by florida63** [comment]
I had seen but it's still boring to know of this patch, even if we do not integrate. 
In my view, we must refocus bugs and patch present on the old wiki.

**Comment by acv** [comment]
I wasn't shooting down the patch, just adding this as a requirement for a PR.

**Comment by acv** [comment]
The pull request is basically complete but could use more testing.

**Comment by mhaas** [comment]
Does this require an update to doc/wifidog_firewall_map.dia?

**Comment by acv** [comment]
Maybe, I don't have dia so I can't see (I always preferred OmniGraffle, which is what I used for the original flow diagram.)

**Comment by acv** [comment]
Fix merged but leaving issue open as reminder to update NEWS file tonight.

**Comment by acv** [comment]
NEWS updated, all done here.
